---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}

library(ggplot2)
library(ggcorrplot)
library(caret)
```

```{r}
data = read.csv("weatherAUS.csv", header=TRUE)
tail(data)
data = na.omit(data)
data$RainTodayNum = as.numeric(data$RainToday)-1
data$RainTomorrowNum = as.numeric(data$RainTomorrow)-1

```

```{r}

ggplot(data,aes(x=data$Pressure9am,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Pressure at 9 am")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$Pressure3pm,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Pressure at 3 pm")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$Pressure3pm-data$Pressure9am,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Change in pressure")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$MaxTemp,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Maximal temperature")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$MinTemp,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Minimal temperature")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$MaxTemp-data$MinTemp,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Temperature range")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$Temp9am,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Temperature at 9 am")+
#ylab(label = "Probability of rain next day")+
theme_minimal()


ggplot(data,aes(x=data$Temp3pm,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Temperature at 3 pm")+
#ylab(label = "Probability of rain next day")+
theme_minimal()


ggplot(data,aes(x=data$Temp9am-data$Temp3pm,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Change in temperature")+
#ylab(label = "Probability of rain next day")+
theme_minimal()


ggplot(data,aes(x=data$Humidity9am ,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Humidity at 9 am")+
#(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$Humidity3pm ,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Humidity at 3 pm")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$Humidity3pm-data$Humidity9am,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Change in humidity")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$WindGustSpeed ,fill=factor(data$RainTomorrow), stat="density")) + geom_density(alpha=0.5)+
xlab(label = "Wind speed")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$WindSpeed9am,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Wind speed at 9 am")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$WindSpeed3pm,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Wind speed at 3 pm")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$WindSpeed3pm-data$WindSpeed9am,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Change in wind speed")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$Cloud9am ,fill=factor(data$RainTomorrow), stat="density")) + geom_density(alpha=0.5)+
xlab(label = "Clouds at 9 am")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$Cloud3pm ,fill=factor(data$RainTomorrow), stat="density")) + geom_density(alpha=0.5)+
xlab(label = "Clouds at 3 pm")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$Cloud3pm-data$Cloud9am,fill=factor(data$RainTomorrow), stat="count")) + geom_density(alpha=0.5)+
xlab(label = "Change in clouds")+
#ylab(label = "Probability of rain next day")+
theme_minimal()


ggplot(data,aes(x=data$Sunshine ,fill=factor(data$RainTomorrow), stat="density")) + geom_density(alpha=0.5)+
xlab(label = "Sunshine")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

ggplot(data,aes(x=data$RainTodayNum ,fill=factor(data$RainTomorrow), stat="density")) + geom_density(alpha=0.5)+
xlab(label = "Rain today")+
#ylab(label = "Probability of rain next day")+
theme_minimal()

```

```{r}
data$TempDiff = data$Temp3pm-data$Temp9am
data$TempRange = data$MaxTemp-data$MinTemp
data$PressureDiff = data$Pressure3pm-data$Pressure9am
data$HumidityDiff = data$Humidity3pm-data$Humidity9am
data$CloudDiff = data$Cloud3pm-data$Cloud9am

numerical_data = data[, c("Pressure9am","Pressure3pm","PressureDiff",
                         "MinTemp","MaxTemp","TempRange","Temp9am", "Temp3pm", "TempDiff",
                         "Humidity9am","Humidity3pm","HumidityDiff",
                         "WindGustSpeed",
                         "Cloud9am","Cloud3pm",
                         "RainTodayNum","RainTomorrowNum",
                         "Sunshine")]


ggcorrplot(corr=cor(numerical_data),hc.order = TRUE, method="square", lab = TRUE, lab_size = 2)

```
Choose values corelated with RainTomorrow
```{r}

useful_data = data[, c("Pressure9am","Pressure3pm",
                         "TempRange","TempDiff",
                         "Humidity9am","Humidity3pm","HumidityDiff",
                         "WindGustSpeed",
                         "Cloud9am","Cloud3pm",
                         "RainTodayNum","RainTomorrowNum",
                         "Sunshine")]

ggcorrplot(corr=cor(useful_data),hc.order = TRUE, method="square", lab = TRUE, lab_size = 2)



```
Choose more or less bitwise incorrelated values
```{r}
independent_data = data[,c("Pressure3pm",
                           "TempDiff","Temp3pm",
                           "Humidity3pm",
                           "WindGustSpeed",
                           "RainTodayNum","RainTomorrowNum",
                           "Sunshine"
                           )]
ggcorrplot(corr=cor(independent_data),hc.order = TRUE, method="square", lab = TRUE, lab_size = 3)

```

Divide data into training and testing datasets
```{r}
set.seed(2901384)
training_index = sample(nrow(independent_data), nrow(independent_data)/2, replace=FALSE)
training_data = independent_data[training_index, ]
test_data = independent_data[-training_index, ]
nrow(training_data)
nrow(test_data)
```


```{r}
model = glm(training_data$RainTomorrowNum~.,
#              training_data$Humidity3pm+
#              training_data$Temp3pm+
 #             training_data$RainTodayNum+
  #            training_data$WindGustSpeed+
   #           training_data$Sunshine+
    #          training_data$TempDiff,
            family=binomial(link="logit"), data = training_data)

```

```{r}
prediction = predict.glm(model, newdata = test_data, type = 'response')
prediction = ifelse(prediction > 0.5 , 1 ,0)
result = data.frame(prediction)
result$prediction = as.factor(result$prediction)
confusionMatrix(result$prediction, as.factor(test_data$RainTomorrowNum))

```
